/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "c2c.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData, de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData, 2)







