/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DE_TU_DARMSTADT_SEEMOO_NFCGATE_NETWORK_C2C_C2C_PB_H_INCLUDED
#define PB_DE_TU_DARMSTADT_SEEMOO_NFCGATE_NETWORK_C2C_C2C_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource {
    de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource_READER = 0,
    de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource_CARD = 1
} de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource;

typedef enum _de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType {
    de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType_INITIAL = 0,
    de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType_CONTINUATION = 1
} de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(512) de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_data_t;
/* Message for passing NFC data between clients */
typedef struct _de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData {
    /* If data is coming from a NFC Card or a NFC Reader */
    de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource data_source;
    /* If data is initial card data or continuation */
    de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType data_type;
    /* The actual bytes to be sent */
    de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_data_t data;
    /* Unix timestamp in millis */
    int64_t timestamp;
} de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource_MIN de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource_READER
#define _de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource_MAX de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource_CARD
#define _de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource_ARRAYSIZE ((de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource)(de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource_CARD+1))

#define _de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType_MIN de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType_INITIAL
#define _de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType_MAX de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType_CONTINUATION
#define _de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType_ARRAYSIZE ((de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType)(de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType_CONTINUATION+1))

#define de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_data_source_ENUMTYPE de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource
#define de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_data_type_ENUMTYPE de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType


/* Initializer values for message structs */
#define de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_init_default {_de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource_MIN, _de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType_MIN, {0, {0}}, 0}
#define de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_init_zero {_de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataSource_MIN, _de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DataType_MIN, {0, {0}}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_data_source_tag 1
#define de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_data_type_tag 2
#define de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_data_tag 3
#define de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_timestamp_tag 4

/* Struct field encoding specification for nanopb */
#define de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    data_source,       1) \
X(a, STATIC,   SINGULAR, UENUM,    data_type,         2) \
X(a, STATIC,   SINGULAR, BYTES,    data,              3) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         4)
#define de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_CALLBACK NULL
#define de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_DEFAULT NULL

extern const pb_msgdesc_t de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_fields &de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_msg

/* Maximum encoded size of messages (where known) */
#define DE_TU_DARMSTADT_SEEMOO_NFCGATE_NETWORK_C2C_C2C_PB_H_MAX_SIZE de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_size
#define de_tu_darmstadt_seemoo_nfcgate_network_c2c_NFCData_size 530

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
