/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DE_TU_DARMSTADT_SEEMOO_NFCGATE_NETWORK_C2S_C2S_PB_H_INCLUDED
#define PB_DE_TU_DARMSTADT_SEEMOO_NFCGATE_NETWORK_C2S_C2S_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode {
    de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode_OP_PSH = 0,
    de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode_OP_SYN = 1,
    de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode_OP_ACK = 2,
    de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode_OP_FIN = 3
} de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(600) de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_data_t;
/* Session management messages */
typedef struct _de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData {
    /* Describes intent of the sender */
    de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode opcode;
    /* Binary blob containing the message content */
    de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_data_t data;
} de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode_MIN de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode_OP_PSH
#define _de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode_MAX de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode_OP_FIN
#define _de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode_ARRAYSIZE ((de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode)(de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode_OP_FIN+1))

#define de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_opcode_ENUMTYPE de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode


/* Initializer values for message structs */
#define de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_init_default {_de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode_MIN, {0, {0}}}
#define de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_init_zero {_de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_Opcode_MIN, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_opcode_tag 1
#define de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_data_tag 2

/* Struct field encoding specification for nanopb */
#define de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    opcode,            1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2)
#define de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_CALLBACK NULL
#define de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_DEFAULT NULL

extern const pb_msgdesc_t de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_fields &de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_msg

/* Maximum encoded size of messages (where known) */
#define DE_TU_DARMSTADT_SEEMOO_NFCGATE_NETWORK_C2S_C2S_PB_H_MAX_SIZE de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_size
#define de_tu_darmstadt_seemoo_nfcgate_network_c2s_ServerData_size 605

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
